#!/bin/bash
# Manual Vercel Deployment Guide

echo "================================"
echo "TAXQUEST APP - DEPLOYMENT GUIDE"
echo "================================"
echo ""
echo "✅ Changes Made:"
echo "  1. Removed 'REFRESH QUEST BANK' button"
echo "  2. Enhanced quiz randomness with:"
echo "     - Dynamic topic selection (10 pool, pick 5)"
echo "     - Session ID unique per request"
echo "     - Temperature 1.0 for max creativity"
echo "     - Console logs for validation"
echo ""
echo "📦 Build Status: ✅ SUCCESS"
echo "   Output: dist/ folder ready"
echo ""
echo "🌐 DEPLOY OPTIONS:"
echo ""
echo "Option 1: Vercel Dashboard (RECOMMENDED)"
echo "  1. Visit: https://vercel.com/dashboard"
echo "  2. Select project: taxquest-app"
echo "  3. Click: Redeploy > Confirm"
echo "  4. Wait 30s for build"
echo "  5. Test: Click 'START NEW QUEST' 3x and verify questions are different"
echo ""
echo "Option 2: Git Push (if repo connected)"
echo "  cd /root/taxquest-app"
echo "  git add ."
echo "  git commit -m 'Fix: Quiz randomness + remove refresh button'"
echo "  git push"
echo "  # Vercel auto-deploys"
echo ""
echo "Option 3: Vercel CLI"
echo "  npx vercel --prod"
echo "  # Follow login prompts in browser"
echo ""
echo "🧪 VALIDATION CHECKLIST:"
echo "  [ ] Open production URL"
echo "  [ ] Open browser console (F12)"
echo "  [ ] Click 'START NEW QUEST'"
echo "  [ ] Check console: Session ID + Sample Q1/Q2"
echo "  [ ] Click 'RETRY QUEST' after finishing"
echo "  [ ] Check console again: NEW Session ID + Different Q1/Q2"
echo "  [ ] Repeat 3x to confirm randomness"
echo ""
echo "Expected Console Output:"
echo "  🎲 Quiz Request - SessionID: 1789520123_42857, Topics: PPh 21 TER, PPN..."
echo "  ✓ Fetched 10 fresh questions from API"
echo "  📋 Sample Q1: PT Maju Jaya membayar gaji karyawan..."
echo "  📋 Sample Q2: Perusahaan PKP dengan omzet..."
echo ""
echo "🔗 Project ID: prj_kkw4NqiueaMIT5EDiHBzya5XF2C7"
echo "🔗 Production URL: https://taxquest-app.vercel.app"
echo ""
echo "================================"
